apiVersion: fhir.imaware.com/v1alpha1
kind: FhirStore
metadata:
  name: test-fhir
  namespace: test
spec:
  datasetID: test-dataset
  fhirStoreID: ethan-fhirstore
  options:
    preventDelete: false
    bigquery:
    - id: bq://imaware-test.test2