---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fhir-operator.fullname" . }}
  labels:
    {{- include "fhir-operator.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      {{- include "fhir-operator.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fhir-operator.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "fhir-operator.serviceAccountName" . }}
      containers:
      - env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
          - name: RELEASE_TAG 
            value: {{ .Values.image.tag }}
          {{- range $key, $val := required "Please make sure the env is set with GCP_LOCATION, GCP_PROJECT" .Values.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end}}
        command:
        - /manager
        {{- range $flag := .Values.commandFlags }}
        - {{ $flag }}
        {{- end}}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - mountPath: /var/secrets/google
          name: google-cloud-key
      terminationGracePeriodSeconds: 10
      volumes:
        - name: google-cloud-key
          secret:
            secretName: {{ include "fhir-operator.serviceAccountName" . | trunc 25 | trimSuffix "-" }}-key
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
