
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - fhir.imaware.com
  resources:
  - fhirresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fhir.imaware.com
  resources:
  - fhirresources/finalizers
  verbs:
  - update
- apiGroups:
  - fhir.imaware.com
  resources:
  - fhirresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fhir.imaware.com
  resources:
  - fhirstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fhir.imaware.com
  resources:
  - fhirstores/finalizers
  verbs:
  - update
- apiGroups:
  - fhir.imaware.com
  resources:
  - fhirstores/status
  verbs:
  - get
  - patch
  - update
