# Default values for order-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of replicas
replicaCount: 1

# -- What namesapce to deploy namespaced resources too
namespace: ""

# -- To create the PSP or not
pspCreate: true 

image:
  # -- Repository hosting the image
  repository: gcr.io/imaware-test/fhir-operator
  # -- ImagePullPolicy settings
  pullPolicy: Always
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: 1.0.0

# -- Image pull secrets for the container registry
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

iamServiceAccount:
  # -- If running in a cluster with Anthos config connector will create GCP IAM resources
  create: true
  # -- (REQUIRED) GCP project
  project: ""
  polices:
  # -- (REQUIRED) role for the fhir operator to edit fhir resources in the project. Project must be set to the GCP project in use.
  - role: roles/healthcare.fhirResourceEditor
    project: ""
  # -- (REQUIRED) role for the fhir operator to edit manage fhir stores in the project. Project must be set to the GCP project in use.
  - role: roles/healthcare.fhirStoreAdmin	
    project: ""
  # -- (REQUIRED) role for the fhir operator use workload identity
  - role: roles/iam.workloadIdentityUser

env:
  # -- (REQUIRED) env var that points to the project in GCP
  GCP_PROJECT: ""
  # -- (REQUIRED) env var that points to the GCP location
  GCP_LOCATION: ""
  # -- env var for enabling debug logging
  DEBUG_ENABLED: "false"

# -- Additional command arguments that can be passed to controller
commandFlags: []

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: "fhir-operator"

# -- Additional pod annotations
podAnnotations: {}

podSecurityContext: 
  # -- Allow pods to run as root
  runAsNonRoot: true


# -- Additional container secuirty context settings
securityContext: {}

resources: 
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

# -- Which node pods should run on
nodeSelector: {}

# -- Which nodes pods should tolerate
tolerations: []

# -- Requirements for pods to run on node
affinity: {}