apiVersion: fhir.imaware.com/v1alpha1
kind: FhirStore
metadata:
  name: ethan-test-fhir
  namespace: ethan-test
spec:
  datasetID: demo-dataset
  fhirStoreID: ethan-test-data
  auth:
    roles/viewer:
      members:
      - "serviceAccount:ethan-local@imaware-test.iam.gserviceaccount.com"




