name: Build and push image

on:
  release:
    types:
      - created

env:
  REGISTRY: ghcr.io/imaware
  IMAGE_NAME: ${{ github.repository }}

jobs:
  fhir-operator:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: bloodbot
          password: ${{ secrets.BOT_TOKEN }}

      # Build the Docker image
      - name: Build
        env:
          DOCKER_BUILDKIT: 1
        run: |
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          echo $TAG
          docker build -t "$REGISTRY"/fhir-operator:"$TAG" .
      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          echo $TAG
          docker push "$REGISTRY"/fhir-operator:"$TAG"
          docker tag "$REGISTRY"/fhir-operator:"$TAG" "$REGISTRY"/fhir-operator:"$GITHUB_SHA"
          docker push "$REGISTRY"/fhir-operator:"$GITHUB_SHA"
          docker tag "$REGISTRY"/fhir-operator:"$TAG" "$REGISTRY"/fhir-operator:latest
          docker push "$REGISTRY"/fhir-operator:latest
      - name: Update Chart Manifest
        run: |
          yq eval ".version = \"${{ steps.bump_version.outputs.next-version }}\"" -i charts/Chart.yaml
      - name: Build and Push chart
        run: |
          helm  package charts
          helm push fhir-operator-${{ github.event.release.tag_name }}.tgz ghcr.io/${{ github.repository_owner }}/fhir-operator-chart
