name: Build and push image

on:
  release:
    types:
      - created

env:
  REGISTRY: ghcr.io/imaware
  IMAGE_NAME: ${{ github.repository }}

jobs:
  fhir-operator:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: bloodbot
          password: ${{ secrets.BOT_TOKEN }}

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: ${{ secrets.IMAWARE_TEST_WIP }}
          service_account: gh-actions-terraform-develop@imaware-test.iam.gserviceaccount.com
      # Setup gcloud CLI
      - name: Set up GCP Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Authenticate to helm registry
        run: |
          helm version
          gcloud auth application-default print-access-token | helm registry login -u oauth2accesstoken \
          --password-stdin https://us-central1-docker.pkg.dev
      # Build the Docker image
      - name: Build
        env:
          DOCKER_BUILDKIT: 1
        run: |
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          echo $TAG
          docker build -t "$REGISTRY"/fhir-operator:"$TAG" .
      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          echo $TAG
          docker push "$REGISTRY"/fhir-operator:"$TAG"
          docker tag "$REGISTRY"/fhir-operator:"$TAG" "$REGISTRY"/fhir-operator:"$GITHUB_SHA"
          docker push "$REGISTRY"/fhir-operator:"$GITHUB_SHA"
          docker tag "$REGISTRY"/fhir-operator:"$TAG" "$REGISTRY"/fhir-operator:latest
          docker push "$REGISTRY"/fhir-operator:latest
      - name: Update Chart Manifest
        run: |
          yq eval ".version = \"${{ github.event.release.tag_name }}\"" -i charts/Chart.yaml
      - name: Build and Push chart
        run: |
          helm  package charts
          helm push fhir-operator-${{ github.event.release.tag_name }}.tgz oci://us-central1-docker.pkg.dev/imaware-artifacts/charts-public

